// ============================================================================
// USA Gummies — Short-Form Video Script Database
// 70+ script templates across 6 categories
// ============================================================================

import { COMPETITORS, CATEGORIES } from './config.mjs';

// Helper: unique ID generator
let _scriptId = 0;
function sid(category) {
  _scriptId++;
  return `${category}-${String(_scriptId).padStart(3, '0')}`;
}

// ---------------------------------------------------------------------------
// CATEGORY A: Ingredient Expose (12 scripts)
// ---------------------------------------------------------------------------
const INGREDIENT_EXPOSE = [
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Titanium Dioxide in Haribo',
    hook: 'I read the label on Haribo Goldbears and found titanium dioxide — banned in European food but perfectly legal here.',
    body: [
      'Show Haribo bag — zoom on ingredient list.',
      'Highlight "titanium dioxide" on the label.',
      'Explain: titanium dioxide is a whitening agent also used in paint and sunscreen.',
      'The EU banned it from food in 2022 over DNA damage concerns.',
      'But in the US? Still in your gummy bears.',
      'Show USA Gummies bag — flip to ingredients. No titanium dioxide. No artificial dyes. Made in America.',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'TITANIUM DIOXIDE',
      'Banned in EU food (2022)',
      'Still legal in US candy',
      'Also used in: paint, sunscreen',
      'USA Gummies: ZERO artificial dyes',
    ],
    visualNotes: 'Close-up label shots. Green screen or countertop. Side-by-side bags. Zoom macro on ingredient text.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'haribo',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: '8 Artificial Dyes in Nerds Gummy Clusters',
    hook: 'There are 8 artificial dyes in Nerds Gummy Clusters. Let me read every single one.',
    body: [
      'Hold up Nerds Gummy Clusters bag.',
      'Flip to ingredient label — start reading dyes one by one.',
      'Red 40, Red 40 Lake, Yellow 5, Yellow 5 Lake, Yellow 6, Blue 1, Blue 2, carmine.',
      'Pause on carmine: "That is crushed cochineal insects. Actual bugs."',
      'Show USA Gummies label: none of that.',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'NERDS GUMMY CLUSTERS',
      '1. Red 40',
      '2. Red 40 Lake',
      '3. Yellow 5',
      '4. Yellow 5 Lake',
      '5. Yellow 6',
      '6. Blue 1',
      '7. Blue 2',
      '8. Carmine (CRUSHED INSECTS)',
      'USA Gummies: 0 artificial dyes',
    ],
    visualNotes: 'Count on fingers or show text appearing one-by-one. Dramatic pause on carmine. Show bug image briefly.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'nerdsGummyClusters',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Crushed Insects in Your Candy',
    hook: 'POV: You find out your kids\' favorite candy has crushed insects in it.',
    body: [
      'Stare at camera, deadpan.',
      '"Carmine. Also called cochineal extract. It is a red dye made from crushed cochineal insects."',
      '"It is in Nerds Gummy Clusters, some yogurts, and a bunch of candy you would never suspect."',
      'Show the actual insect (stock image). Show the red dye it produces.',
      '"There are plant-based alternatives. Some brands just choose not to use them."',
      'Hold up USA Gummies. "No carmine. No bugs. Just fruit-based colors."',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      'CARMINE = CRUSHED INSECTS',
      'Found in: Nerds Gummy Clusters, yogurt, candy',
      'Plant-based alternatives exist',
      'USA Gummies: NO carmine, NO artificial dyes',
    ],
    visualNotes: 'Green screen with bug close-up. Shock face. Label close-ups.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'nerdsGummyClusters',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Where Sour Patch Kids Are Actually Made',
    hook: 'I checked where Sour Patch Kids are ACTUALLY made. It is not America.',
    body: [
      'Show Sour Patch Kids bag. "This feels like an American candy, right? The branding, the vibe."',
      'Flip to back of bag. "Manufactured in Hamilton, Ontario, Canada."',
      '"Some varieties are made in Monterrey, Mexico."',
      '"Owned by Mondelez International — a multinational conglomerate."',
      '"Also contains Red 40, Yellow 5, Yellow 6, Blue 1."',
      'Hold up USA Gummies. "Made in America. Natural colors. That is the difference."',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'SOUR PATCH KIDS',
      'Made in: Canada & Mexico',
      'Owner: Mondelez (multinational)',
      'Contains: Red 40, Yellow 5, Yellow 6, Blue 1',
      'USA Gummies: Made in AMERICA',
    ],
    visualNotes: 'Map graphic showing Canada/Mexico. Side-by-side with USA Gummies. Label close-ups.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'sourPatchKids',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Mars Broke Their Promise',
    hook: 'In 2016, Mars promised to remove all artificial colors from their candy. It is 2026. They still have not.',
    body: [
      'Show headline/screenshot of 2016 Mars announcement.',
      '"Mars said they would remove artificial colors from their entire portfolio."',
      '"That was TEN YEARS ago."',
      'Show Skittles Gummies label: Red 40, Yellow 5, Yellow 6, Blue 1.',
      '"Still there. Every single one."',
      '"Some brands actually followed through. USA Gummies never had artificial dyes in the first place."',
    ],
    cta: 'Follow if you care what is in your food.',
    onScreenText: [
      'MARS INC. (2016): "We will remove artificial colors"',
      'MARS INC. (2026): Still has Red 40, Yellow 5, Yellow 6, Blue 1',
      '10 YEARS. Zero change.',
      'USA Gummies: Never had artificial dyes',
    ],
    visualNotes: 'Screenshot of 2016 article. Calendar flipping. Current label. Split screen then vs now.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'skittlesGummies',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Trans Fat in Airheads',
    hook: 'Airheads still contain partially hydrogenated soybean oil. That is trans fat.',
    body: [
      'Show Airheads wrapper. Flip to ingredients.',
      '"Partially hydrogenated soybean oil. That is the scientific name for trans fat."',
      '"The FDA determined trans fats are NOT generally recognized as safe."',
      '"Most food companies reformulated years ago. Airheads? Still there."',
      '"Oh, and they are owned by a Dutch-Italian company. Not American."',
      'Show USA Gummies. "No trans fats. No artificial anything. Made in the USA."',
    ],
    cta: 'Check the link in bio before your next grocery run.',
    onScreenText: [
      'AIRHEADS',
      'Contains: partially hydrogenated soybean oil',
      '= TRANS FAT',
      'FDA: not safe',
      'Owner: Dutch-Italian conglomerate',
      'USA Gummies: No trans fats',
    ],
    visualNotes: 'Label zoom. FDA document flash. Company HQ in Netherlands.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'airheads',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Trolli Is Made in Mexico',
    hook: 'Trolli is made in Linares, Mexico, owned by an Italian company, and sold to you as if it is American.',
    body: [
      'Show Trolli bag. "Looks American, right? Bright colors, sold at every gas station."',
      'Flip to label. "Manufactured in Linares, Mexico."',
      '"Owned by Ferrara Candy, which is owned by Ferrero Group — headquartered in Luxembourg."',
      '"Contains titanium dioxide, Red 40, Yellow 5, Yellow 6, Blue 1."',
      '"Italian-owned, Mexican-made, full of artificial dyes. But sure, it is an American candy."',
    ],
    cta: 'USA Gummies dot com. That is all.',
    onScreenText: [
      'TROLLI',
      'Made in: Linares, MEXICO',
      'Owner: Ferrero Group (ITALY)',
      'HQ: Luxembourg',
      'Contains: titanium dioxide + 4 artificial dyes',
    ],
    visualNotes: 'Map showing Italy/Mexico/Luxembourg. Label close-ups. Flag overlays.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'trolli',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'White Mineral Oil in Swedish Fish',
    hook: 'Swedish Fish contains white mineral oil. Yes, the same base ingredient as baby oil.',
    body: [
      'Show Swedish Fish bag. Zoom on ingredients.',
      '"White mineral oil. Right there on the label."',
      '"Mineral oil is a petroleum byproduct. It is in baby oil, laxatives, and apparently your candy."',
      '"Swedish Fish is made by the same company as Sour Patch Kids — Mondelez."',
      '"There are candy companies that do not put petroleum byproducts in their gummy bears."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'SWEDISH FISH',
      'Contains: white mineral oil',
      'Mineral oil = petroleum byproduct',
      'Also in: baby oil, laxatives',
      'USA Gummies: No mineral oil',
    ],
    visualNotes: 'Baby oil bottle next to Swedish Fish. Ingredient zoom. Petroleum barrel stock image.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels'],
    competitor: 'sourPatchKids',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Haribo Dual Standard',
    hook: 'Haribo in Germany vs Haribo in America — they are selling us the worse version.',
    body: [
      'Show two Haribo bags side by side (US vs German label).',
      '"In Germany, Haribo uses natural plant and fruit extracts for color."',
      '"In America? Red 40, Yellow 5, Yellow 6, Blue 1. All artificial."',
      '"Same company. Same brand. They literally make a better version — just not for us."',
      '"They know artificial dyes are a problem. They reformulated in Europe. They just did not bother here."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'HARIBO GERMANY: natural colors',
      'HARIBO USA: Red 40, Yellow 5, Yellow 6, Blue 1',
      'Same company. Different standards.',
      'They make a better version — not for you.',
    ],
    visualNotes: 'Split screen: German label vs US label. Highlight differences. Flag overlays.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'haribo',
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'The Candy Aisle Audit',
    hook: 'I spent a week reading every candy label at Target. The results were terrifying.',
    body: [
      'Montage of flipping candy bags at Target (or similar store).',
      '"Titanium dioxide. Red 40. Carmine. Yellow 5. Partially hydrogenated oil. Over and over."',
      '"Out of about 30 gummy candies on the shelf, only a handful had no artificial dyes."',
      '"Most were made outside the US — Canada, Mexico, Germany, Turkey."',
      '"The candy aisle is an ingredient minefield and most people never flip the bag."',
      'Show USA Gummies. "This is what clean ingredients actually look like."',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'TARGET CANDY AISLE AUDIT',
      'Titanium dioxide: found in 8+ products',
      'Red 40: found in 20+ products',
      'Made outside US: majority',
      'Clean ingredients: rare',
    ],
    visualNotes: 'Montage of label readings. Counter tallying bad ingredients. Store aisle B-roll.',
    estimatedDuration: 45,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'The "Natural Flavors" Trick',
    hook: 'When a candy label says "natural flavors" it does not mean what you think it means.',
    body: [
      '"Natural flavors" is one of the most misleading terms in food.',
      'By FDA definition, it just means the flavor was derived from a natural source at some point.',
      'It can still be heavily processed. It can contain solvents and preservatives.',
      'Some brands use it as a catch-all to hide dozens of sub-ingredients.',
      'Real transparency means listing what the flavors actually are — fruit juice, plant extracts, specific sources.',
      'Show USA Gummies ingredient list with specific, readable ingredients.',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      '"NATURAL FLAVORS"',
      'FDA definition: derived from natural source',
      'Can be heavily processed',
      'Can hide dozens of sub-ingredients',
      'Look for: specific sources listed',
    ],
    visualNotes: 'FDA document snippets. Label comparisons. Magnifying glass effect on fine print.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('expose'),
    category: CATEGORIES.INGREDIENT_EXPOSE.id,
    title: 'Ferrero Owns Everything',
    hook: 'An Italian company called Ferrero now owns Trolli, Nerds, Brach\'s, SweeTarts, and Butterfinger. All of them.',
    body: [
      '"You think you are buying from different candy brands. You are not."',
      '"Ferrero Group, headquartered in Luxembourg, bought Ferrara Candy in 2018."',
      '"That gave them Trolli, Nerds, Brach\'s, SweeTarts, Laffy Taffy, Butterfinger, Crunch, and more."',
      '"Most of it is manufactured in Mexico."',
      '"One Italian conglomerate controls a massive chunk of the American candy aisle."',
      '"Support actual American-made candy instead."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'FERRERO GROUP (Italy/Luxembourg)',
      'Owns: Trolli, Nerds, Brach\'s, SweeTarts',
      'Also: Laffy Taffy, Butterfinger, Crunch',
      'Most made in: MEXICO',
      'Support American-made instead',
    ],
    visualNotes: 'Web diagram showing all brands connecting to Ferrero. Map of Mexico factory locations.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
];

// ---------------------------------------------------------------------------
// CATEGORY B: Made in USA Patriotic (12 scripts)
// ---------------------------------------------------------------------------
const MADE_IN_USA = [
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Name One American-Made Candy',
    hook: 'Name a candy that is ACTUALLY made in America. I will wait.',
    body: [
      'Stitch/duet format or direct to camera.',
      '"Haribo? Germany. Trolli? Mexico. Sour Patch Kids? Canada. Nerds? Mexico."',
      '"Most of the candy aisle is foreign-made and foreign-owned."',
      '"We started USA Gummies because we got tired of it."',
      '"All American Gummy Bears. Made in the USA. No artificial dyes. That is it."',
    ],
    cta: 'USA Gummies dot com. That is all.',
    onScreenText: [
      'Name an American-made candy...',
      'Haribo: GERMANY',
      'Trolli: MEXICO',
      'Sour Patch Kids: CANADA',
      'Nerds: MEXICO',
      'USA Gummies: MADE IN AMERICA',
    ],
    visualNotes: 'Country flags appearing next to each brand. Map pins. USA Gummies reveal at end.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'I Stopped Buying Foreign Candy',
    hook: 'I stopped buying foreign-made candy. Here is what happened.',
    body: [
      '"I started checking where my candy was made. Almost everything was foreign."',
      '"Canada, Mexico, Germany, Turkey, Brazil — everywhere but here."',
      '"So I stopped. Cold turkey. Only American-made from that point."',
      '"My options shrunk dramatically. The candy aisle got real small real fast."',
      '"But the stuff I did find? Better ingredients. No artificial dyes. Actually made here."',
      '"That is when I found out about USA Gummies. All American Gummy Bears."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'THE FOREIGN CANDY EXPERIMENT',
      'Step 1: Check labels',
      'Step 2: Realize almost everything is imported',
      'Step 3: Switch to American-made only',
      'Result: Better ingredients, less junk',
    ],
    visualNotes: 'Store aisle montage. Flipping labels. Rejection pile vs accept pile. USA Gummies as the payoff.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'The Candy Aisle Is Lying',
    hook: 'The candy aisle is lying to you about "American" brands.',
    body: [
      '"Sour Patch Kids feels American, right? Made in Canada and Mexico."',
      '"Trolli has stars and stripes energy. Made in Mexico, owned by Italy."',
      '"Nerds Gummy Clusters. The packaging screams USA. Manufactured in Mexico, owned by Italy."',
      '"The branding is American. The manufacturing is not. The ownership is not."',
      '"If you actually want American-made candy, you have to look past the packaging."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'THE CANDY AISLE IS LYING',
      'American branding ≠ American made',
      'Check: Where is it manufactured?',
      'Check: Who owns the company?',
      'Check: What is in the ingredients?',
    ],
    visualNotes: 'Pulling back the curtain concept. Packaging vs reality split screen.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: '4th of July American-Made Only',
    hook: 'This 4th of July, I am only serving American-made candy. Here is what made the cut.',
    body: [
      '"Independence Day. Celebrating America. So let us actually buy American."',
      '"I went through every candy at the store and checked where it was made."',
      '"Most of the red, white, and blue themed candy? Imported."',
      '"The irony of serving foreign-made candy on Independence Day."',
      'Show the final spread with USA Gummies front and center.',
      '"Made in America. No artificial dyes. All natural. This is the 4th of July candy table."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      '4TH OF JULY CANDY TABLE',
      'Rule: American-made ONLY',
      'Failed: most "patriotic" candy is imported',
      'Winner: USA Gummies',
      'Made in America. No artificial junk.',
    ],
    visualNotes: 'Patriotic table setup. Red, white, blue decorations. Candy sorting. Final spread reveal.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Buy American Challenge',
    hook: 'Buy American Challenge: I tried to fill an entire candy bowl with only American-made candy.',
    body: [
      'Walk into store with a bowl.',
      'Start checking labels — one by one.',
      '"Mexico. No. Canada. No. Germany. No. Mexico again. No."',
      'The bowl stays empty for a while. Dramatic.',
      'Finally find American-made options. USA Gummies goes in.',
      '"It should not be this hard to buy American-made candy in America."',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'BUY AMERICAN CHALLENGE',
      'Goal: Fill a candy bowl — American-made only',
      'Mexico... Canada... Germany...',
      'It should not be this hard.',
    ],
    visualNotes: 'Store walking montage. Empty bowl. Label checking. Dramatic reveals of country of origin.',
    estimatedDuration: 40,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'American Jobs in Candy',
    hook: 'Every bag of foreign-made candy you buy is a job that could have been here.',
    body: [
      '"Trolli is made in Mexico. Sour Patch Kids — Canada and Mexico. Nerds — Mexico."',
      '"Those are manufacturing jobs. Packaging jobs. Quality control jobs. Supply chain jobs."',
      '"All of those could be in American towns. American factories. American paychecks."',
      '"When you choose American-made, you are not just choosing a product. You are choosing a paycheck for someone here."',
      '"USA Gummies. Made in America. Every bag."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'FOREIGN-MADE CANDY = FOREIGN JOBS',
      'Manufacturing, packaging, QC, supply chain',
      'Those jobs could be HERE',
      'Buy American = American paychecks',
    ],
    visualNotes: 'Factory B-roll (American manufacturing). Map showing jobs leaving. American workers.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Memorial Day Made in America',
    hook: 'Memorial Day weekend. Honoring Americans who served. The least you can do is serve American-made candy.',
    body: [
      '"This weekend is about honoring service and sacrifice."',
      '"And then we fill our party tables with candy made in Mexico, Canada, and Germany."',
      '"It is a small thing. But small things matter."',
      '"American-made gummy bears. No artificial dyes. All natural flavors."',
      '"USA Gummies. Made in America. For Americans."',
    ],
    cta: 'USA Gummies dot com. That is all.',
    onScreenText: [
      'MEMORIAL DAY',
      'Honor American sacrifice',
      'Serve American-made',
      'USA Gummies: Made in America',
    ],
    visualNotes: 'American flags. BBQ/party setup. Respectful tone. Product placement natural.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Presidents Day — Who Makes Our Candy',
    hook: 'Happy Presidents Day. Let us talk about who actually makes your candy.',
    body: [
      '"We celebrate American leadership today. But our candy aisle is led by foreign companies."',
      '"Ferrero — Italy. Haribo — Germany. Perfetti Van Melle — Netherlands. Mondelez — multinational."',
      '"These companies control most of what Americans eat for candy."',
      '"Not a single one is American-owned and American-made across the board."',
      '"Time to change that."',
    ],
    cta: 'USA Gummies. Made in America. Link in bio.',
    onScreenText: [
      'WHO MAKES YOUR CANDY?',
      'Ferrero: ITALY',
      'Haribo: GERMANY',
      'Perfetti Van Melle: NETHERLANDS',
      'USA Gummies: AMERICA',
    ],
    visualNotes: 'Presidential imagery. Corporate HQ locations on map. American flag transition.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Made in America Hits Different',
    hook: '"Made in America" is not just a label. It is a standard.',
    body: [
      '"When something is made here, it is subject to American labor laws. American food safety standards. American environmental regulations."',
      '"When your candy is made in Mexico or Turkey, different rules apply."',
      '"Different oversight. Different standards. Different accountability."',
      '"I am not saying foreign food is bad. I am saying American-made means American accountability."',
      '"USA Gummies. Made here. Accountable here."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'MADE IN AMERICA = AMERICAN STANDARDS',
      'Labor laws. Food safety. Environmental regs.',
      'Foreign-made = different rules',
      'American-made = American accountability',
    ],
    visualNotes: 'Factory compliance imagery. American flag. Clean facility B-roll.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Flip the Bag Challenge',
    hook: 'Flip the Bag Challenge: Grab any candy from your pantry and tell me where it is made.',
    body: [
      '"Grab any candy. Any. Flip the bag. Find where it is manufactured."',
      '"Comment below what you found."',
      '"I guarantee most of you will find Canada, Mexico, Germany, or somewhere else."',
      '"Finding American-made candy is like finding a needle in a haystack."',
      '"USA Gummies. American-made. Every single bag."',
      '"Take the challenge. Flip the bag."',
    ],
    cta: 'Comment what you found. Link in bio.',
    onScreenText: [
      'FLIP THE BAG CHALLENGE',
      'Step 1: Grab any candy',
      'Step 2: Find "manufactured in"',
      'Step 3: Comment what you found',
    ],
    visualNotes: 'Challenge format. Quick flips of multiple bags. Engagement-optimized.',
    estimatedDuration: 20,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'The American Candy Shelf',
    hook: 'I made a shelf in my pantry for American-made candy only. It is almost empty.',
    body: [
      'Show pantry shelf.',
      '"I decided to separate my candy by where it is made."',
      '"Foreign-made shelf — packed. Mexico, Canada, Germany, Turkey."',
      '"American-made shelf — almost empty."',
      '"That is a problem. In America, we should be able to fill a shelf with American-made candy."',
      '"Starting with these." Show USA Gummies bags.',
    ],
    cta: 'Help me fill the shelf. Link in bio.',
    onScreenText: [
      'AMERICAN CANDY SHELF',
      'Foreign-made: FULL',
      'American-made: almost empty',
      'That is a problem.',
    ],
    visualNotes: 'Pantry organization. Two shelves visual comparison. Satisfying organization vibes.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('usa'),
    category: CATEGORIES.MADE_IN_USA.id,
    title: 'Labor Day American Made',
    hook: 'Labor Day celebrates American workers. Here is which candy brands actually employ them.',
    body: [
      '"Labor Day is about the American workforce."',
      '"So which candy brands actually have American workers making their products?"',
      '"Trolli? Workers in Mexico. Nerds? Mexico. Sour Patch Kids? Canada and Mexico."',
      '"When you buy foreign-made candy, those manufacturing jobs are not here."',
      '"USA Gummies. Made by American workers. In America. Happy Labor Day."',
    ],
    cta: 'USA Gummies. Made in America. Link in bio.',
    onScreenText: [
      'LABOR DAY',
      'Which candy employs American workers?',
      'Trolli: Mexico',
      'Nerds: Mexico',
      'Sour Patch Kids: Canada/Mexico',
      'USA Gummies: AMERICA',
    ],
    visualNotes: 'American workers imagery. Factory setting. Patriotic but not over-the-top.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
];

// ---------------------------------------------------------------------------
// CATEGORY C: Parent / Health Angle (12 scripts)
// ---------------------------------------------------------------------------
const PARENT_HEALTH = [
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: '3 Ingredients That Would Surprise You',
    hook: '3 ingredients in your kid\'s gummy bears that would surprise you.',
    body: [
      '"Number one: titanium dioxide. A whitening agent also used in paint. Found in Haribo and Trolli."',
      '"Number two: carmine. A red dye made from crushed cochineal insects. Found in Nerds Gummy Clusters."',
      '"Number three: white mineral oil. A petroleum byproduct. Found in Swedish Fish."',
      '"I am not making this up. These are on the label. You just have to actually read it."',
      '"USA Gummies has none of these. No artificial dyes. No weird additives."',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      '3 INGREDIENTS IN YOUR KID\'S CANDY',
      '1. Titanium dioxide (paint ingredient)',
      '2. Carmine (crushed insects)',
      '3. White mineral oil (petroleum)',
      'USA Gummies: NONE of these',
    ],
    visualNotes: 'Countdown format. Each ingredient gets a dramatic reveal. Labels shown.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Pediatrician Said Check for Dyes',
    hook: 'My pediatrician told me to check for artificial dyes. Here is what I found in my kid\'s candy.',
    body: [
      '"At our last checkup, the pediatrician mentioned artificial food dyes."',
      '"Some studies link Red 40 and Yellow 5 to hyperactivity in children."',
      '"California now requires warning labels on foods with certain dyes."',
      '"So I went home and checked our candy drawer. Red 40 was in almost everything."',
      '"Haribo. Trolli. Sour Patch Kids. Skittles Gummies. All of them."',
      '"We switched to dye-free options. USA Gummies was the easiest swap — they taste like actual gummy bears, not health food."',
    ],
    cta: 'Check the link in bio before your next grocery run.',
    onScreenText: [
      'PEDIATRICIAN: Check for artificial dyes',
      'Red 40 linked to hyperactivity in studies',
      'California requires warning labels',
      'Found Red 40 in: almost every candy',
      'Switch: USA Gummies (no artificial dyes)',
    ],
    visualNotes: 'Mom/dad POV. Candy drawer dump. Label reading montage. Swap visual.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Dye-Free Switch Changed Everything',
    hook: 'The dye-free candy switch that changed everything for my kid\'s behavior.',
    body: [
      '"I am not a doctor. This is just what happened with my family."',
      '"We cut artificial food dyes from our kids\' diet. Including candy."',
      '"Within two weeks, we noticed a difference. Less hyperactivity. Better focus."',
      '"Could be coincidence. Could be placebo. But the research supports it."',
      '"The EU requires warning labels on foods with these dyes. We do not."',
      '"We kept the change. USA Gummies is our go-to for gummy bears now."',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'DYE-FREE EXPERIMENT',
      'Cut artificial dyes from diet',
      '2 weeks: noticed behavioral difference',
      'EU requires warning labels on these dyes',
      'USA does not',
    ],
    visualNotes: 'Family vibe. Kitchen setting. Before/after subtle. Not medical claims — personal story.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Lunchbox Candy Swap',
    hook: 'I swapped every candy in my kid\'s lunchbox for dye-free alternatives. Here is what stayed and what went.',
    body: [
      'Show original lunchbox candy stash.',
      'Check each one: "Red 40. Gone. Yellow 5. Gone. Titanium dioxide. Gone."',
      'Show the swap pile.',
      '"This is harder than it sounds. Most candy at the grocery store has artificial dyes."',
      '"But it is doable. And the kids did not even notice the switch with the gummy bears."',
      'Show USA Gummies in lunchbox.',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'LUNCHBOX CANDY SWAP',
      'OUT: Red 40, Yellow 5, titanium dioxide',
      'IN: natural colors, no artificial dyes',
      'Kids did not notice the switch',
    ],
    visualNotes: 'Lunchbox layout. Before/after. Sorting process. Kid-friendly vibes.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Halloween Candy Bowl Audit',
    hook: 'I audited my kid\'s Halloween candy. 90% had artificial dyes.',
    body: [
      'Dump the Halloween bag on the table.',
      'Start sorting: artificial dyes vs no artificial dyes.',
      '"Red 40. Red 40. Yellow 5. Red 40 again. Titanium dioxide. Red 40."',
      'The artificial dye pile grows massive. The clean pile is tiny.',
      '"This is what we are handing out to kids on Halloween."',
      '"Next year, we are handing out USA Gummies. No artificial dyes. Made in America."',
    ],
    cta: 'Save this for Halloween season.',
    onScreenText: [
      'HALLOWEEN CANDY AUDIT',
      'Artificial dyes: 90%',
      'No artificial dyes: 10%',
      'Red 40 count: lost track',
    ],
    visualNotes: 'Table sorting montage. Two piles growing. Dramatic size difference. Satisfying sorting.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'The After-School Snack Test',
    hook: 'I gave my kids two gummy bears and asked them to pick a favorite. They had no idea one was dye-free.',
    body: [
      'Set up blind taste test with kids.',
      '"One has artificial dyes. One does not. Let us see which one they pick."',
      'Kids taste both. Give their honest reaction.',
      '"They could not tell the difference. Or they picked the dye-free one."',
      '"The idea that you need artificial dyes for good candy is a myth."',
      '"If kids cannot tell, why are we feeding them chemicals?"',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'BLIND TASTE TEST',
      'Artificial dyes vs No artificial dyes',
      'Kids could not tell the difference',
      'Why use chemicals if they are not needed?',
    ],
    visualNotes: 'Kids eating gummy bears. Fun, authentic reactions. Kitchen counter setting.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'California Dye Warning Labels',
    hook: 'California now requires warning labels on candy with certain artificial dyes. Here is why.',
    body: [
      '"California passed a law requiring warning labels on foods with Red 3, Red 40, Yellow 5, Yellow 6, Blue 1, Blue 2, and Green 3."',
      '"The warning says these dyes may cause behavioral issues in children."',
      '"This is based on years of research."',
      '"The EU has required similar warnings since 2010."',
      '"Other states are following California\'s lead."',
      '"Or you could just buy candy without artificial dyes in the first place."',
    ],
    cta: 'Follow if you care what is in your food.',
    onScreenText: [
      'CALIFORNIA WARNING LABELS',
      'Red 3, Red 40, Yellow 5, Yellow 6',
      'Blue 1, Blue 2, Green 3',
      '"May cause behavioral issues in children"',
      'EU has required warnings since 2010',
    ],
    visualNotes: 'News headline screenshots. Warning label mockup. California/EU comparison.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'What I Wish I Knew Sooner',
    hook: 'What I wish I knew before I had kids: how to read a candy label.',
    body: [
      '"Nobody teaches you this. You just grab what looks good and toss it in the cart."',
      '"But once you start reading labels, you cannot unsee it."',
      '"Step 1: Flip the bag. Step 2: Look for Red 40, Yellow 5, Yellow 6, Blue 1. Step 3: Check where it is made."',
      '"If it has artificial dyes and it is made outside the US, there are better options."',
      '"It takes 10 extra seconds at the store. Your kids are worth 10 seconds."',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      'HOW TO READ A CANDY LABEL',
      '1. Flip the bag',
      '2. Check for: Red 40, Yellow 5, Yellow 6, Blue 1',
      '3. Check: Where is it made?',
      '10 seconds. Worth it.',
    ],
    visualNotes: 'Tutorial format. Step-by-step label reading. Store setting or kitchen counter.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'The Birthday Party Dilemma',
    hook: 'Planning a birthday party and trying to avoid artificial dyes is a nightmare.',
    body: [
      '"Candy bags, pinata filler, cake decorations — everything has Red 40."',
      '"I spent three hours trying to find dye-free party candy."',
      '"Most of what is marketed as \'natural\' still has dyes buried in the ingredient list."',
      '"The solution: buy from brands that are actually transparent about ingredients."',
      '"USA Gummies made the party bag. Gummy bears with no artificial dyes. The kids loved them."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'DYE-FREE BIRTHDAY PARTY',
      'Challenge: find candy without Red 40',
      'Time spent: 3 hours',
      'Solution: USA Gummies',
    ],
    visualNotes: 'Party prep montage. Frustrated label reading. Bright party table at the end.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Europe Protects Kids Better',
    hook: 'In Europe, candy with artificial dyes has a warning label. In America, it has a cartoon mascot.',
    body: [
      '"The EU requires foods with Red 40, Yellow 5, and other dyes to carry a warning."',
      '"It says: may have an adverse effect on activity and attention in children."',
      '"That same candy is sold in the US — with no warning. Same dyes. Same amounts."',
      '"Haribo reformulated for Europe. Natural colors. For America? Artificial."',
      '"We deserve the same standard our kids are not less important."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'EUROPE: Warning label on artificial dyes',
      'AMERICA: No warning. Cartoon mascot.',
      'Same candy. Different standards.',
      'Our kids deserve better.',
    ],
    visualNotes: 'EU warning label visual. US candy packaging comparison. Split screen.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'haribo',
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'The Snack Drawer Reset',
    hook: 'I reset my entire snack drawer. Here is what got cut and what stayed.',
    body: [
      'Open snack drawer. Dump everything out.',
      'Go through each item: check ingredients, check origin.',
      '"Artificial dyes? Out. Trans fat? Out. Made in Mexico? I will find an American alternative."',
      'Show the new, curated snack drawer.',
      '"It is not about being perfect. It is about being informed."',
      '"USA Gummies earned a permanent spot."',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'SNACK DRAWER RESET',
      'Criteria: No artificial dyes, American-made preferred',
      'Cut: most of it',
      'Kept: clean label brands',
    ],
    visualNotes: 'Satisfying organization content. ASMR potential. Before/after. Clean pantry vibes.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('parent'),
    category: CATEGORIES.PARENT_HEALTH.id,
    title: 'Reading Labels with My Kid',
    hook: 'I taught my 8-year-old to read candy labels. Now she is the ingredient police.',
    body: [
      '"She picks up a bag and the first thing she does is flip it over."',
      '"Mom, this has Red 40." "Dad, this one is made in Mexico."',
      '"It started as a game. Now she actually cares about what is in her food."',
      '"She told her friend at school that gummy bears can have titanium dioxide in them. The teacher looked it up. She was right."',
      '"Teaching kids to read labels is a life skill."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'INGREDIENT POLICE (age 8)',
      '"Mom, this has Red 40"',
      '"This one is made in Mexico"',
      'Teaching kids to read labels = life skill',
    ],
    visualNotes: 'Parent-child shopping trip. Cute kid moments. Label reading together. Heartwarming.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
];

// ---------------------------------------------------------------------------
// CATEGORY D: Comparison / Switch (12 scripts)
// ---------------------------------------------------------------------------
const COMPARISON = [
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Haribo vs USA Gummies Side by Side',
    hook: 'I switched from Haribo to an American-made gummy bear. Side by side comparison.',
    body: [
      'Place both bags on the table. Show front packaging.',
      'Flip both bags. Compare ingredient lists.',
      '"Haribo: sugar, glucose syrup, artificial colors including Red 40, Yellow 5, Yellow 6, Blue 1, titanium dioxide."',
      '"USA Gummies: sugar, glucose syrup, natural flavors, plant and fruit-based colors. No artificial dyes."',
      'Open both bags. Compare the actual gummy bears visually.',
      '"Haribo is shiny, almost plastic looking. USA Gummies looks more natural, less glossy."',
      'Taste test. Honest reaction.',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'HARIBO vs USA GUMMIES',
      'Haribo: 4 artificial dyes + titanium dioxide',
      'USA Gummies: 0 artificial dyes',
      'Haribo: Made in Germany',
      'USA Gummies: Made in America',
    ],
    visualNotes: 'Clean countertop. Side by side. Macro shots of both bears. Split screen eating.',
    estimatedDuration: 40,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'haribo',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'German vs American Haribo',
    hook: 'Haribo in Germany vs Haribo in America. They are selling us the worse version.',
    body: [
      'Show German Haribo ingredients: fruit and plant concentrates for color.',
      'Show American Haribo ingredients: Red 40, Yellow 5, Yellow 6, Blue 1.',
      '"Same company. Same brand. Two completely different products."',
      '"They KNOW how to make gummy bears without artificial dyes. They do it in Europe."',
      '"They just choose not to do it here."',
      '"USA Gummies never had artificial dyes. It is not a reformulation. It is how they started."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'HARIBO GERMANY: natural plant & fruit colors',
      'HARIBO USA: Red 40, Yellow 5, Yellow 6, Blue 1',
      'Same company. Different products.',
      'They know better. They just do not care.',
    ],
    visualNotes: 'Import German bag if possible or show label screenshots. Direct comparison.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'haribo',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Why European Candy Tastes Different',
    hook: 'The REAL reason European candy tastes different. They banned these ingredients.',
    body: [
      '"People always say European candy tastes better. There is a reason."',
      '"The EU banned titanium dioxide from food. They require warning labels on artificial dyes."',
      '"So candy makers in Europe use natural colors and cleaner formulations."',
      '"American candy makers? They use the cheaper stuff because they can."',
      '"It is not that European candy is magic. It is that their regulators actually protect consumers."',
      '"You can get that same clean standard here. You just have to choose it."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'WHY EUROPEAN CANDY TASTES BETTER',
      'EU banned titanium dioxide in food',
      'EU requires dye warning labels',
      'US: no ban, no warnings',
      'Same ingredients are available here — brands just choose not to use them',
    ],
    visualNotes: 'EU vs US regulation comparison. Flag visuals. Ingredient label comparisons.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Trolli vs USA Gummies Origin Check',
    hook: 'Trolli says it is fun and trendy. Let me show you where it is actually made.',
    body: [
      'Show Trolli bag — colorful, fun branding.',
      'Flip to back. "Manufactured in Linares, Mexico."',
      '"Owned by Ferrero Group, an Italian conglomerate headquartered in Luxembourg."',
      'Show ingredients: titanium dioxide, Red 40, Yellow 5, Yellow 6, Blue 1.',
      'Show USA Gummies bag. "Made in America. No artificial dyes."',
      '"Same category. Very different standards."',
    ],
    cta: 'Check the link in bio before your next grocery run.',
    onScreenText: [
      'TROLLI: Fun branding, questionable ingredients',
      'Made in: Mexico',
      'Owner: Italian conglomerate',
      'Contains: titanium dioxide + 4 artificial dyes',
      'USA Gummies: Made in AMERICA, 0 dyes',
    ],
    visualNotes: 'Branding vs reality. Pull back the curtain. Label reveals.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'trolli',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Ingredient Count Challenge',
    hook: 'Let us count: how many ingredients you cannot pronounce in your gummy bears?',
    body: [
      'Pick up multiple candy brands one by one.',
      '"Haribo: Red 40, Yellow 5, Yellow 6, Blue 1, titanium dioxide. That is 5 sketchy ones."',
      '"Nerds Gummy Clusters: 8 artificial dyes plus carmine. That is 9."',
      '"Trolli: titanium dioxide, Red 40, Yellow 5, Yellow 6, Blue 1. Five."',
      '"USA Gummies: zero. None. You can pronounce every single ingredient."',
      '"The brand with the shortest list of weird stuff wins."',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'SKETCHY INGREDIENT COUNT',
      'Haribo: 5',
      'Nerds Gummy Clusters: 9',
      'Trolli: 5',
      'USA Gummies: 0',
    ],
    visualNotes: 'Scoreboard format. Running tally. Each brand getting a score. USA Gummies at zero.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Price Per Bag Comparison',
    hook: 'People say clean ingredient candy is too expensive. Let us do the math.',
    body: [
      'Show prices of common gummy bears at a typical store.',
      '"Haribo 5oz bag: around $2.50. Trolli 5oz: around $2.50."',
      '"USA Gummies: a little more, but here is what you get for it."',
      '"No artificial dyes. No titanium dioxide. No crushed insects. Made in America."',
      '"You are paying for what is NOT in it. And for American jobs."',
      '"A dollar more for cleaner ingredients and American manufacturing? That is the easiest trade I have ever made."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'PRICE CHECK',
      'Haribo 5oz: ~$2.50 (artificial dyes, Germany)',
      'Trolli 5oz: ~$2.50 (artificial dyes, Mexico)',
      'USA Gummies: a little more',
      'No dyes. No junk. Made in America.',
      'Worth it? You decide.',
    ],
    visualNotes: 'Price tags. Calculator. Value comparison chart. Not apologetic about price.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Gummy Bear Transparency Test',
    hook: 'The transparency test: hold your gummy bear up to a light.',
    body: [
      'Hold Haribo bear up to light — very vivid, almost neon color.',
      'Hold USA Gummies bear up to light — more natural, warm tones.',
      '"Artificial dyes give candy that hyper-bright, unnatural look."',
      '"Natural colors are a bit more muted. That is actually a good sign."',
      '"If your gummy bear glows like a highlighter, ask yourself why."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'TRANSPARENCY TEST',
      'Artificial dyes: neon, hyper-bright',
      'Natural colors: warm, muted',
      'If it glows like a highlighter... why?',
    ],
    visualNotes: 'Backlit gummy bears. Beautiful macro photography. Light shining through.',
    estimatedDuration: 20,
    platforms: ['tiktok', 'reels'],
    competitor: 'haribo',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'The 10-Second Label Test',
    hook: 'The 10-second test that tells you if your candy is worth eating.',
    body: [
      '"Step 1: Flip the bag. 2 seconds."',
      '"Step 2: Look for Red 40, Yellow 5, titanium dioxide. 5 seconds."',
      '"Step 3: Check country of origin. 3 seconds."',
      '"If you find artificial dyes and it is made outside the US, you can do better."',
      '"10 seconds. That is all it takes to make a smarter choice."',
      'Demonstrate with multiple bags in rapid succession.',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      '10-SECOND LABEL TEST',
      '2 sec: Flip the bag',
      '5 sec: Check for dyes',
      '3 sec: Check country of origin',
      'Artificial dyes + foreign-made = skip it',
    ],
    visualNotes: 'Stopwatch running. Quick label flips. Pass/fail overlay on each bag.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Sour Patch Kids vs USA Gummies Country',
    hook: 'Sour Patch Kids are made in Canada. I found an American-made alternative that slaps.',
    body: [
      'Show Sour Patch Kids. "Love them. Grew up on them."',
      'Flip the bag. "Made in Hamilton, Ontario, Canada. Huh."',
      '"Also has Red 40, Yellow 5, Yellow 6, Blue 1."',
      '"I wanted something similar — sour, fruity, gummy — but American-made and no artificial dyes."',
      '"USA Gummies. All American Gummy Bears. Made in the USA. Clean ingredients."',
      '"Different flavor profile, but honestly? I am not going back."',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'SOUR PATCH KIDS: Canada, 4 artificial dyes',
      'USA GUMMIES: America, 0 artificial dyes',
      'The switch was easier than I thought.',
    ],
    visualNotes: 'Both bags side by side. Eating comparison. Honest, not scripted reactions.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'sourPatchKids',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Grocery Store Showdown',
    hook: 'Grocery store showdown: I compared every gummy bear brand on the shelf.',
    body: [
      'Walk the candy aisle. Pick up each gummy bear brand.',
      'Rapid-fire: "Haribo — Germany, artificial dyes. Trolli — Mexico, artificial dyes. Black Forest — could not confirm US made. Store brand — made in Mexico."',
      '"Out of six brands, one was clearly American-made with no artificial dyes."',
      'Reveal USA Gummies.',
      '"This should not be a scavenger hunt."',
    ],
    cta: 'USA Gummies dot com. That is all.',
    onScreenText: [
      'GUMMY BEAR SHOWDOWN',
      'Haribo: Germany, artificial dyes',
      'Trolli: Mexico, artificial dyes',
      'Store brand: Mexico',
      'USA Gummies: AMERICA, clean',
    ],
    visualNotes: 'Aisle walk. Rapid picks. Quick verdict per brand. Tournament bracket graphic.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'Nerds Gummy Clusters Breakdown',
    hook: 'Nerds Gummy Clusters might be the most chemically loaded candy on the shelf. Let me show you.',
    body: [
      'Show Nerds Gummy Clusters bag. "This is one of the top-selling candies in America right now."',
      '"Made in Mexico. Owned by Ferrero Group — Italian conglomerate."',
      '"Ingredient list: 8 artificial dyes. EIGHT."',
      '"Plus carmine — that is crushed cochineal insects for red coloring."',
      '"Compare that to a brand with zero artificial dyes and no crushed bugs."',
      '"Popularity does not mean quality."',
    ],
    cta: 'Follow if you care what is in your food.',
    onScreenText: [
      'NERDS GUMMY CLUSTERS',
      'Made in: Mexico',
      'Owner: Italy',
      'Artificial dyes: 8',
      'Also: crushed insects (carmine)',
      'Popularity ≠ Quality',
    ],
    visualNotes: 'Label zoom. Counting dyes. Bug imagery. Popularity vs quality graph.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: 'nerdsGummyClusters',
  },
  {
    id: sid('compare'),
    category: CATEGORIES.COMPARISON.id,
    title: 'My Candy Tier List',
    hook: 'Ranking gummy bears by ingredients and where they are made. Final tier list.',
    body: [
      'Set up tier list format (S through F).',
      '"F tier: Nerds Gummy Clusters. 8 artificial dyes, carmine, made in Mexico."',
      '"D tier: Trolli. Titanium dioxide, artificial dyes, made in Mexico."',
      '"C tier: Haribo. Artificial dyes in US version, at least some made in Wisconsin."',
      '"B tier: Sour Patch Kids. Artificial dyes, but at least no titanium dioxide in the original."',
      '"S tier: USA Gummies. No artificial dyes. Made in America. Clean ingredient list."',
      '"This tier list is based on ingredients and origin, not nostalgia."',
    ],
    cta: 'Would you switch? Link in bio.',
    onScreenText: [
      'GUMMY TIER LIST (by ingredients)',
      'F: Nerds (8 dyes + bugs)',
      'D: Trolli (titanium dioxide + dyes)',
      'C: Haribo (dyes, some US-made)',
      'B: Sour Patch Kids (dyes, no TiO2)',
      'S: USA Gummies (0 dyes, American)',
    ],
    visualNotes: 'Tier list template. Drag and drop aesthetic. Each brand gets placed with reasoning.',
    estimatedDuration: 40,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
];

// ---------------------------------------------------------------------------
// CATEGORY E: Trending / Reactive (10 scripts — template format)
// ---------------------------------------------------------------------------
const TRENDING = [
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Breaking: FDA Ingredient News',
    hook: '[Breaking news about food ingredient] — here is what you need to know about your candy.',
    body: [
      'Reference the specific news story (fill in when posting).',
      '"This affects [specific candy brands]."',
      'Show which products contain the ingredient in question.',
      '"Check your pantry. Check your kids\' lunchboxes."',
      '"Brands with clean ingredient lists are not affected. USA Gummies has none of this."',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'BREAKING: [FDA news headline]',
      'Affected: [list brands]',
      'Check your pantry',
      'USA Gummies: NOT affected',
    ],
    visualNotes: 'News headline format. Urgent but factual. Breaking news aesthetic.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['news headline', 'affected brands', 'specific ingredient'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'State Banning Red 40',
    hook: 'States banning Red 40 — is your favorite candy affected?',
    body: [
      '"Following California, more states are introducing bills to ban or label artificial dyes."',
      '"Red 40 is in almost every major candy brand."',
      'Run through affected brands quickly.',
      '"This is not a fringe issue anymore. It is going mainstream."',
      '"If your candy brand has to reformulate because of a ban, maybe it should not have been in there in the first place."',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      'RED 40 BANS SPREADING',
      'California: signed into law',
      '[State]: bill introduced',
      'Red 40 found in: Haribo, Trolli, Sour Patch Kids, Skittles',
      'USA Gummies: never had Red 40',
    ],
    visualNotes: 'Map showing states with legislation. News clips. List of affected brands.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['state name', 'bill status'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Viral Ingredient Trend Response',
    hook: 'Everyone is talking about [trending ingredient topic]. Let me show you which candy has it.',
    body: [
      'Reference the viral trend (TikTok, news, etc.).',
      '"People are just now finding out about [ingredient]. But it has been on labels this whole time."',
      'Show specific products that contain it.',
      '"This is why reading labels matters. This stuff is not hidden — it is just ignored."',
      '"USA Gummies has none of this. Never did."',
    ],
    cta: 'Follow if you care what is in your food.',
    onScreenText: [
      '[TRENDING INGREDIENT] is going viral',
      'Found in: [candy brands]',
      'It was on the label the whole time',
      'USA Gummies: clean since day one',
    ],
    visualNotes: 'Stitch/duet the original viral video. Add ingredient label proof.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels'],
    competitor: null,
    isTemplate: true,
    fillIn: ['trending ingredient', 'affected brands', 'viral video reference'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'FDA Announcement Reaction',
    hook: 'The FDA just announced [X]. Check your candy drawer.',
    body: [
      'Show FDA announcement (screenshot or headline).',
      '"Here is what this means in plain English."',
      'Explain the ingredient or policy change simply.',
      '"These brands are affected: [list]."',
      '"These brands are not: [list including USA Gummies]."',
      '"Save this. Send it to someone who needs to see it."',
    ],
    cta: 'Comment "LABEL" and I will send you the full ingredient comparison.',
    onScreenText: [
      'FDA ANNOUNCEMENT',
      '[Plain English explanation]',
      'Affected: [brands]',
      'Not affected: USA Gummies',
    ],
    visualNotes: 'FDA logo. Official document screenshots. List format.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['FDA announcement', 'affected brands'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Back to School Candy Alert',
    hook: 'Back to school. Here is what is in the candy you are packing in lunchboxes.',
    body: [
      '"Back to school season. Every parent is packing lunchboxes right now."',
      '"Let me show you what is in the most common lunchbox candy."',
      'Rapid-fire label reads of popular candy.',
      '"Red 40, Yellow 5, titanium dioxide, carmine — all going to school with your kid."',
      '"Swap suggestion: USA Gummies. No artificial dyes. Made in America. Fits in a lunchbox."',
    ],
    cta: 'Save this for your next Target run.',
    onScreenText: [
      'BACK TO SCHOOL CANDY CHECK',
      'What is in your kid\'s lunchbox?',
      'Red 40, Yellow 5, titanium dioxide...',
      'Swap: USA Gummies (no artificial dyes)',
    ],
    visualNotes: 'Lunchbox packing montage. Label zooms. School bus B-roll. Mom/dad POV.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: false,
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Tariff and Trade News',
    hook: '[Country] tariff news just dropped. Here is how it affects your candy.',
    body: [
      'Reference specific tariff or trade news.',
      '"Most Americans do not realize how much candy is imported."',
      '"Trolli — Mexico. Haribo — Germany. Sour Patch Kids — Canada."',
      '"When tariffs change, prices change. On foreign goods."',
      '"American-made candy? Not affected by import tariffs. Just saying."',
    ],
    cta: 'USA Gummies. Made in America. Link in bio.',
    onScreenText: [
      'TARIFF NEWS',
      'Imported candy prices may change',
      'Affected: Mexico-made, Canada-made, Europe-made',
      'Not affected: American-made',
    ],
    visualNotes: 'News headlines. Map of trade routes. Dollar signs. Prices going up.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['country', 'tariff details'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Recall or Contamination News',
    hook: 'Another food recall just hit. Is your candy on the list?',
    body: [
      'Reference specific recall (fill in when posting).',
      '"Food safety recalls happen more often than you think."',
      '"When products are manufactured overseas, the supply chain is longer and harder to monitor."',
      '"Shorter supply chain = faster response, more oversight, more accountability."',
      '"American-made products go through American food safety inspections."',
    ],
    cta: 'Follow for more ingredient breakdowns.',
    onScreenText: [
      'FOOD RECALL ALERT',
      'Longer supply chain = more risk',
      'American-made = American oversight',
      'Shorter chain = faster response',
    ],
    visualNotes: 'Recall notice screenshots. Supply chain map. Factory compliance imagery.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['recall details', 'affected products'],
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Election Season — American Made',
    hook: 'Everyone is talking about American jobs right now. Let me show you where your candy jobs went.',
    body: [
      '"Every election, politicians talk about bringing jobs back to America."',
      '"Meanwhile, the candy aisle is full of Mexican-made, Canadian-made, European-made products."',
      '"Trolli — Mexico. Nerds — Mexico. Sour Patch Kids — Canada."',
      '"Every bag is jobs. Manufacturing, packaging, shipping, quality control."',
      '"You can bring jobs back without waiting for an election. Buy American-made."',
    ],
    cta: 'USA Gummies. Made in America. Link in bio.',
    onScreenText: [
      'ELECTION TALK: BRING JOBS BACK',
      'Start with your candy.',
      'Foreign-made candy = foreign jobs',
      'Buy American = American jobs',
    ],
    visualNotes: 'No partisan imagery. Factory B-roll. Worker imagery. Shopping choice.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: false,
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'Summer Candy Season',
    hook: 'Summer candy season is here. Let me save you from the artificial dye minefield.',
    body: [
      '"Pool parties. Barbecues. Road trips. Summer means candy."',
      '"But before you stock up, let me show you what to avoid."',
      'Quick label reads of summer staples.',
      '"Red 40, Yellow 5, titanium dioxide — it is in everything."',
      '"Here is my summer candy swap list. Starts with USA Gummies."',
    ],
    cta: 'Save this for summer shopping.',
    onScreenText: [
      'SUMMER CANDY GUIDE',
      'Avoid: Red 40, Yellow 5, titanium dioxide',
      'Swap to: dye-free alternatives',
      '#1 Pick: USA Gummies',
    ],
    visualNotes: 'Summer vibes. Pool/BBQ setting. Cooler full of candy. Beach/outdoor.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: false,
  },
  {
    id: sid('trend'),
    category: CATEGORIES.TRENDING.id,
    title: 'New Year Health Reset Candy',
    hook: 'New year health reset? Start with your candy drawer.',
    body: [
      '"Everyone is resetting their diet in January."',
      '"You are cutting carbs, adding vegetables, drinking water."',
      '"But have you checked your candy drawer? Your kids\' snacks?"',
      '"Red 40, Yellow 5, titanium dioxide — that stuff does not belong in a health reset."',
      '"Swap to dye-free candy. Small change, big difference."',
    ],
    cta: 'USA Gummies. No artificial junk. Link in bio.',
    onScreenText: [
      'NEW YEAR RESET',
      'You fixed your diet. Fix your candy drawer.',
      'Out: artificial dyes',
      'In: clean ingredient candy',
    ],
    visualNotes: 'Clean kitchen. Health reset aesthetic. Pantry organization. Fresh start vibes.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels'],
    competitor: null,
    isTemplate: false,
  },
];

// ---------------------------------------------------------------------------
// CATEGORY F: Storytelling / Brand (12 scripts)
// ---------------------------------------------------------------------------
const STORYTELLING = [
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Why I Started a Candy Company',
    hook: 'I started a candy company because I was tired of feeding my kids chemicals.',
    body: [
      '"It started at a grocery store. Reading labels. Realizing almost every candy had artificial dyes."',
      '"Red 40. Yellow 5. Titanium dioxide. Carmine."',
      '"I thought — someone has to be making gummy bears without this stuff."',
      '"And someone has to be making them in America."',
      '"So I started USA Gummies. All American Gummy Bears. No artificial dyes. Made in the USA."',
      '"It is not easy competing against billion-dollar foreign companies. But it is worth it."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'WHY I STARTED USA GUMMIES',
      'Tired of artificial dyes in every candy',
      'Wanted American-made, clean ingredients',
      'Built it myself',
    ],
    visualNotes: 'Authentic, raw founder story. Kitchen or office setting. Personal, not polished.',
    estimatedDuration: 35,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Day X of Building a Candy Brand',
    hook: 'Day [X] of building an American candy brand from scratch.',
    body: [
      'Show the daily grind — packing orders, checking inventory, social media, customer emails.',
      '"Today I [specific daily task]."',
      '"Running a small candy company means you do everything."',
      '"But every bag that ships is American-made, dye-free, and something I am proud of."',
      '"Against Haribo, Trolli, Sour Patch Kids — giants. But we have something they do not."',
      '"We are actually made in America. And our ingredients are actually clean."',
    ],
    cta: 'Follow the journey. Link in bio.',
    onScreenText: [
      'DAY [X]',
      'Small brand vs billion-dollar competitors',
      'Every bag: American-made, dye-free',
      'The underdog story continues',
    ],
    visualNotes: 'Day-in-the-life format. Authentic. Raw. Phone-shot quality is fine.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels'],
    competitor: null,
    isTemplate: true,
    fillIn: ['day number', 'daily task'],
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Zero Artificial Dyes — How We Do It',
    hook: 'What it takes to make gummy bears with ZERO artificial dyes.',
    body: [
      '"Every major gummy bear brand uses artificial dyes. It is cheaper. It is easier."',
      '"Going dye-free means using plant and fruit-based colors."',
      '"That costs more. It is harder to source. The colors are not as neon."',
      '"But the result is a gummy bear you can feel good about eating. And feeding to your kids."',
      '"We chose the harder path because it is the right one."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'ZERO ARTIFICIAL DYES',
      'Harder? Yes. More expensive? Yes.',
      'Worth it? Absolutely.',
      'Plant and fruit-based colors only',
    ],
    visualNotes: 'Behind the scenes feel. Ingredient sourcing. Color comparisons. Process shots.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'First Order Memory',
    hook: 'I still remember our first order. One bag. One customer. That was everything.',
    body: [
      '"Our first sale was one bag of gummy bears."',
      '"I packed it myself. Wrote a thank-you note by hand. Drove it to the post office."',
      '"Today we ship a lot more than that. But I still remember that feeling."',
      '"Starting from zero against billion-dollar brands is terrifying. But every order matters."',
      '"If you have ever ordered from us — thank you. You are why we keep going."',
    ],
    cta: 'Try them yourself — link in bio.',
    onScreenText: [
      'ORDER #1',
      '1 bag. 1 customer. Everything.',
      'From zero to here.',
      'Every order matters.',
    ],
    visualNotes: 'Emotional founder moment. Old photos if available. Packing orders. Growth montage.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'David vs Goliath — Small Brand',
    hook: 'We are a small American candy brand competing against Haribo, Trolli, and Sour Patch Kids. Here is what that is like.',
    body: [
      '"They have billion-dollar marketing budgets. We have a phone and a passion for clean ingredients."',
      '"They have shelf space in every store in America. We are building one customer at a time."',
      '"They have artificial dyes and foreign factories. We have transparency and American manufacturing."',
      '"The odds are not in our favor. But that has never stopped anyone worth rooting for."',
    ],
    cta: 'Root for the underdog. Link in bio.',
    onScreenText: [
      'DAVID vs GOLIATH',
      'Them: billion-dollar budgets, foreign factories',
      'Us: clean ingredients, American-made',
      'Root for the underdog',
    ],
    visualNotes: 'Underdog narrative. Small operation footage. Vs the corporate giants concept.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Customer Reviews Montage',
    hook: 'I read our customer reviews when I need a reminder of why we do this.',
    body: [
      'Show real customer reviews one by one.',
      '"My kids love them and I can feel good about it."',
      '"Finally, gummy bears without artificial junk."',
      '"These taste way better than I expected for dye-free candy."',
      '"Made in America. That sealed the deal."',
      '"Every review like this makes the hard days worth it."',
    ],
    cta: 'Join them. Link in bio.',
    onScreenText: [
      'CUSTOMER REVIEWS',
      '[Real review quotes]',
      'This is why we do it.',
    ],
    visualNotes: 'Screenshot reviews. Heartfelt reading. Mix of funny and touching reviews.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'The Ingredient Promise',
    hook: 'Here is a promise: I will never put artificial dyes in USA Gummies. Ever.',
    body: [
      '"Some companies start clean and then cut corners as they grow."',
      '"More volume means pressure to reduce costs. Artificial dyes are cheap."',
      '"I am making this public promise: USA Gummies will never have artificial dyes."',
      '"No Red 40. No Yellow 5. No titanium dioxide. No carmine. Ever."',
      '"If that means we grow slower, fine. Some things are more important than growth."',
    ],
    cta: 'USA Gummies. Made in America. No artificial junk. Link in bio.',
    onScreenText: [
      'THE PROMISE',
      'No artificial dyes. EVER.',
      'No Red 40. No Yellow 5.',
      'No titanium dioxide. No carmine.',
      'Growth < Integrity',
    ],
    visualNotes: 'Direct to camera. Serious, sincere. No gimmicks. Personal commitment.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Behind the Scenes Packing',
    hook: 'Behind the scenes of an American candy company. No fancy factory tour — just reality.',
    body: [
      'Show the real packing process — orders, labels, boxes.',
      '"This is what a small American candy brand looks like."',
      '"No corporate office. No 30-person marketing team."',
      '"Just good product, clean ingredients, and grinding every day."',
      '"Every bag you order goes through these hands."',
      '"That is the difference between a small brand and a corporation."',
    ],
    cta: 'Link in bio — USA Gummies, made in America.',
    onScreenText: [
      'BEHIND THE SCENES',
      'Small brand. Big mission.',
      'Every bag goes through these hands.',
      'Not corporate. Personal.',
    ],
    visualNotes: 'Warehouse/packing footage. ASMR potential. Satisfying packing shots. Raw and real.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'What They Told Me Would Fail',
    hook: '"You cannot compete with Haribo on gummy bears." That is what they told me.',
    body: [
      '"You cannot compete with Haribo. You cannot compete with Trolli."',
      '"The candy market is locked up. The shelf space is owned."',
      '"And honestly? They are right about the shelf space. For now."',
      '"But they are wrong about everything else."',
      '"Consumers are waking up. They want clean ingredients. They want American-made."',
      '"The old guard is not ready for that. We are."',
    ],
    cta: 'Follow the journey. Link in bio.',
    onScreenText: [
      '"You cannot compete with Haribo"',
      'WATCH ME.',
      'Consumers want: clean ingredients + American-made',
      'Old guard is not ready. We are.',
    ],
    visualNotes: 'Motivational founder content. Quote graphics. Building montage.',
    estimatedDuration: 30,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Milestone Celebration',
    hook: 'We just hit [milestone]. Here is what it took to get here.',
    body: [
      '"[X] orders. [X] bags shipped. [X] customers."',
      '"That number means nothing to Haribo or Trolli. They do that in an hour."',
      '"But for a small American candy brand? This is everything."',
      '"Every order is someone choosing American-made. Choosing clean ingredients."',
      '"Choosing us over the giants. That is humbling."',
      '"Thank you. On to the next milestone."',
    ],
    cta: 'Be part of the next milestone. Link in bio.',
    onScreenText: [
      'MILESTONE: [X]',
      'Small for them. Everything for us.',
      'American-made. Clean ingredients.',
      'Thank you.',
    ],
    visualNotes: 'Celebration but humble. Order counter. Growth graph. Thank-you vibe.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
    isTemplate: true,
    fillIn: ['milestone number', 'metric type'],
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'Late Night Packing Orders',
    hook: 'It is 11 PM and I am packing orders. This is what building a brand looks like.',
    body: [
      'Dimly lit workspace. Orders spread out.',
      '"Everyone sees the brand on social media. Nobody sees this."',
      '"The late nights. The packing. The labels. The customer emails at midnight."',
      '"But every bag that goes out is American-made, dye-free, and mine."',
      '"Not Ferrero\'s. Not Mondelez\'s. Not Mars\'s. Mine."',
      '"And that makes the late nights worth it."',
    ],
    cta: 'Link in bio. Support small. Support American.',
    onScreenText: [
      '11 PM. Still packing.',
      'What building a brand actually looks like.',
      'Not corporate. Personal.',
    ],
    visualNotes: 'Late night aesthetic. Desk lamp. Lo-fi vibes. Authentic and raw.',
    estimatedDuration: 25,
    platforms: ['tiktok', 'reels'],
    competitor: null,
  },
  {
    id: sid('story'),
    category: CATEGORIES.STORYTELLING.id,
    title: 'The Name USA Gummies',
    hook: 'People ask why we named it USA Gummies. The answer is simple.',
    body: [
      '"Because that is exactly what it is."',
      '"Gummy bears. Made in the USA. No tricks. No misleading branding."',
      '"Too many candy brands have American vibes but foreign manufacturing."',
      '"We wanted the name to be a promise. If it says USA, it better be made in the USA."',
      '"USA Gummies. The name is the mission."',
    ],
    cta: 'USA Gummies dot com. That is all.',
    onScreenText: [
      'WHY "USA GUMMIES"?',
      'Because that is what it is.',
      'The name is the promise.',
      'Made in the USA. Period.',
    ],
    visualNotes: 'Logo reveal. Brand story. Simple, clean. Name graphic.',
    estimatedDuration: 20,
    platforms: ['tiktok', 'reels', 'shorts'],
    competitor: null,
  },
];

// ---------------------------------------------------------------------------
// Export the full database
// ---------------------------------------------------------------------------
export const SCRIPTS_DB = [
  ...INGREDIENT_EXPOSE,
  ...MADE_IN_USA,
  ...PARENT_HEALTH,
  ...COMPARISON,
  ...TRENDING,
  ...STORYTELLING,
];

export const SCRIPTS_BY_CATEGORY = {
  [CATEGORIES.INGREDIENT_EXPOSE.id]: INGREDIENT_EXPOSE,
  [CATEGORIES.MADE_IN_USA.id]: MADE_IN_USA,
  [CATEGORIES.COMPARISON.id]: COMPARISON,
  [CATEGORIES.PARENT_HEALTH.id]: PARENT_HEALTH,
  [CATEGORIES.TRENDING.id]: TRENDING,
  [CATEGORIES.STORYTELLING.id]: STORYTELLING,
};

// Stats
export function getStats() {
  const total = SCRIPTS_DB.length;
  const byCategory = {};
  for (const [catId, scripts] of Object.entries(SCRIPTS_BY_CATEGORY)) {
    byCategory[catId] = scripts.length;
  }
  const templates = SCRIPTS_DB.filter((s) => s.isTemplate).length;
  const readyToShoot = total - templates;
  return { total, byCategory, templates, readyToShoot };
}

export default SCRIPTS_DB;
